[project]
name = "mock-exporter"
version = "0.1.0"
description = "Django Web App with Prometheus Metrics"
dependencies = [
    "django>=4.2",
    "prometheus-client>=0.19.0",
]

[tool.uv]
dev-dependencies = []
